#!/bin/bash
# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

export SHELL=/bin/bash
export TERM=screen-256color

function get_hostname {
  export SHORTNAME=${HOSTNAME%%.*}
}

function git_branch() { 
  gitbranch=$(git branch 2>/dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'); 
}

function user_color {
  id | grep "root" > /dev/null
  RETVAL=$?
  if [[ $RETVAL == 0 ]]; then
    usercolor="[0;31m";
  else
    usercolor="[0;32m";
  fi
}

function settitle() {
  u=${USERNAME}
  h="$u@${HOSTNAME}"
  echo -ne "\e]2;$h\a\e]1;$h\a";
}

# Set prompt and window title
inputcolor='[0;37m'
cwdcolor='[0;34m'
host_name='[1;31m'
branchcolor='[0;36m'
user_color
PROMPT_COMMAND='settitle; git_branch; get_hostname; history -a;'
PS1='\[\e${cwdcolor}\][${PWD}]\[\e${branchcolor}\]${gitbranch}\n\[\e${usercolor}\][\u]\[\e${host_name}\][${SHORTNAME}]\[\e${inputcolor}\] $ '
export PS1

HISTCONTROL=ignoreboth

umask 027

pushd()
{
  if [ $# -eq 0 ]; then
    DIR="${HOME}"
  else
    DIR="$1"
  fi

  builtin pushd "${DIR}" > /dev/null
  #echo -n "DIRSTACK: "
  #dirs
}

pushd_builtin()
{
  builtin pushd > /dev/null
  #echo -n "DIRSTACK: "
  #dirs
}

popd()
{
  builtin popd > /dev/null
  #echo -n "DIRSTACK: "
  #dirs
}

showd()
{
    echo -n "DIRSTACK: "
    dirs
}

alias cd='pushd'
alias b='popd'
alias flip='pushd_builtin'
alias sd='showd'

export EDITOR='vim'

# Stay in same folder after ssh, yay!
ssh() {
  `which ssh` $1 -t "cd `pwd`; $SHELL --login"
  #command ssh $1 -t "cd `pwd`; $SHELL --login"
}


#source ~/.dotfiles/cluster-rc/bashrc
source ~/.dotfiles/bash_aliases







