
" leader is \ by default

" manage plugins with vundle
source $HOME/.vim/settings/bundle.vim
" install plugins with :PluginInstall in vim


" autocomplete
let g:ycm_autoclose_preview_window_after_completion=1
map <leader>g  :YcmCompleter GoToDefinitionElseDeclaration<CR>

let python_highlight_all=1

au GUIEnter * set vb t_vb=
colorscheme solarized
let g:solarized_termcolors=256
let g:solarized_termtrans=1
let g:solarized_visibility = "high"
let g:solarized_contrast = "high"
set t_Co=256

" reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
	\| exe "normal! g'\"" | endif
endif

" If doing a diff. Upon writing changes to file, automatically update the differences
autocmd BufWritePost * if &diff == 1 | diffupdate | endif

set list!
set listchars=tab:▸\ ,trail:◦,extends:»,precedes:«
set noeb vb t_vb=
set nostartofline
set binary

if has('persistent_undo')        "check if your vim version supports it
	set undofile                 "turn on the feature
	set undodir=$HOME/.vim/undo  "directory where the undo files will be stored
endif

source $HOME/.vim/settings/config.vim
source $HOME/.vim/settings/maps.vim
" source $HOME/.vim/settings/autocmds.vim

" Uncomment the following to have Vim jump to the last position when reopening a file
if has("autocmd")
    au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif


